-- Config
require("config.options")
require("config.keymaps")
require("config.autocmds")

-- Plugins
require("plugins.avante")
require("plugins.barbar")
require("plugins.blink")
require("plugins.copilot")
require("plugins.formatting")
require("plugins.git")
require("plugins.fzflua")
require("plugins.lsp")
require("plugins.linting")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.snacks")
require("plugins.smear_cursor")
require("plugins.origami")
require("plugins.logsitter")
require("plugins.mini-clue")
require("plugins.grug-far")
require("plugins.leetcode")
require("plugins.noice")
require("plugins.flash")
require("plugins.mini-surround")

require("plugins.misc")
